runtime: python
env: flex
# how to config debug https://cloud.google.com/debugger/docs/setup/python#console
# debug ref https://console.cloud.google.com/debug?app=GAE%3Adefault%4020211217t054929&cloudshell=false&project=tinder-standup-comic

#https://cloud.google.com/appengine/docs/standard/python3/runtime
entrypoint: gunicorn -b :5000 -w 1 main:app

runtime_config:
    python_version: 3.7
    
  
# This sample incurs costs to run on the App Engine flexible environment. 
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1



# only for flexible environment
# The standard environment doesn't support as granular resource specification as the flexible environment, there is no resources config in its app.yaml Reference. It only supports selecting pre-defined instance classes. From the same doc:
resources:
  cpu: 2
  memory_gb: 9
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 1
    
network:
  forwarded_ports:
    - 5000/tcp